// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ivjbvnitpaqurqpclrad.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml2amJ2bml0cGFxdXJxcGNscmFkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwMzczNTUsImV4cCI6MjA2ODYxMzM1NX0.j2bqe5eDTgz5T_h7cCAJKWyRq0e3jsOEcwUo3Zt-oS0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});